Repository arkain123/Sweet-Minuette-Bot, pull requests merged in 2024-03, with the labels that each got.

#1 cyberpunk 2077
  controller/huy, pipiska, popa.py
Labels: enhancement

#2 Cyberpunk 2088
  controller/Sosat.py
  main.py
Labels: enhancement

#4 123
  controller/Sosat.py
Labels: bug

#5 change 10 to 3
  controller/Sosat.py
Labels: bug

#16 Massive issue fixes
  controller/mafia.py
Labels: bug

#18 added /sus easter egg
  controller/eastereggs.py
Labels: enhancement

#19 recoded role assign logic
  controller/mafia.py
Labels: enhancement

#20 added testers tribute list
  data/testers.py
Labels: documentation

#21 small personal changes
  data/testers.py
Labels: bug, documentation

#22 getting ready for open test
  controller/Sosat.py
  main.py
  start.bat
Labels: enhancement
